<div class="row">
    <?= $this->form()->openTag($form) ?>
        <div>
            <?= $this->formRow($form->get('username')) ?>
        </div>
        <div>
            <?= $this->formRow($form->get('password')) ?>
        </div>
        <?= $this->formElement($form->get('login')) ?>
    <?= $this->form()->closeTag() ?>
</div>
<a class="btn btn-xs btn-default" href="<?= $this->url('auth/forgotPassword') ?>"><?= $this->translate('forgot.password') ?></a>
<a class="btn btn-xs btn-default" href="<?= $this->url('auth/resendRegisterMail') ?>"><?= $this->translate('resend.register.mail') ?></a>