<h1><?= $this->translate('edit.user') ?></h1>
<div class="row">
    <?= $this->form()->openTag($form) ?>
        <div class="col-xs-12">
            <?= $this->formRow($form->get('username')) ?>
        </div>
        <div class="col-xs-12">
            <?= $this->formRow($form->get('email')) ?>
        </div>
        <div class="col-xs-12">
            <?= $this->formRow($form->get('role')) ?>
        </div>
        <div class="col-xs-12">
            <?= $this->formElement($form->get('save')) ?>
        </div>
    <?= $this->form()->closeTag() ?>
</div>
