<table class="table table-hover">
    <thead>
        <tr>
            <th><?= $this->translate('id') ?></th>
            <th><?= $this->translate('username') ?></th>
            <th><?= $this->translate('role') ?></th>
            <th><?= $this->translate('email') ?></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <?php if ($paginator->count() < 1): ?>
        <tr>
            <td colspan="5"><?= $this->translate('no.results') ?></td>
        </tr>
        <?php endif ?>
        <?php foreach ($paginator->getCurrentItems() as $item): ?>
        <tr>
            <td><?= $item['id'] ?></td>
            <td><?= $item['username'] ?></td>
            <td><?= $item['role'] ?></td>
            <td><?= $item['email'] ?></td>
            <td>
                <a href="<?= $this->url('user/edit', ['id' => $item['id']]) ?>" class="btn btn-default">
                    <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                </a>
                <a href="<?= $this->url('user/delete', ['id' => $item['id']]) ?>" class="btn btn-default">
                    <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                </a>
            </td>
        </tr>
        <?php endforeach ?>
    </tbody>
</table>
<?= $this->paginationControl($paginator, null, 'zend-bricks/bricks-common/partial/pagination.phtml', ['route' => 'user/list']) ?>