<a href="<?= $this->url('profileoption/create') ?>" class="btn btn-success pull-right">
    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> <?= $this->translate('add.profileoption') ?>
</a>
<table class="table">
    <thead>
        <tr>
            <th><?= $this->translate('id') ?></th>
            <th><?= $this->translate('name') ?></th>
            <th><?= $this->translate('input.type') ?></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <?php if ($paginator->count() < 1): ?>
        <tr>
            <td colspan="4"><?= $this->translate('no.results') ?></td>
        </tr>
        <?php endif ?>
        <?php foreach ($paginator as $item): ?>
        <tr>
            <td><?= $item['id'] ?></td>
            <td><?= $item['name'] ?></td>
            <td><?= $item['inputType'] ?></td>
            <td>
                <a href="<?= $this->url('profileoption/edit', ['id' => $item['id']]) ?>" title="<?= $this->translate('edit') ?>" class="btn btn-default">
                    <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                </a>
                <a href="<?= $this->url('profileoption/delete', ['id' => $item['id']]) ?>" title="<?= $this->translate('delete') ?>" class="btn btn-default">
                    <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                </a>
            </td>
        </tr>
        <?php endforeach ?>
    </tbody>
</table>
<?= $this->paginationControl($paginator, null, 'zend-bricks/bricks-common/partial/pagination.phtml', ['route' => 'profileoption/list']) ?>