<?= $this->doctype(); ?>
<html lang="<?= \Locale::getDefault() ?>">
    <head>
        <meta charset="utf-8">
    </head>
    <body style="padding: 20px">
        <table align="center" style="background-color: #444; border-radius: 10px; border-spacing: 0">
            <tbody>
                <tr>
                    <td style="width: 50px"></td>
                    <td>
                        <h1 align="center" style="color: #fff; margin-top: 20px">Example Application</h1>
                    </td>
                    <td style="width: 50px"></td>
                </tr>
                <tr>
                    <td style="width: 50px"></td>
                    <td style="background-color: #fff; border-radius: 10px; padding: 20px">
                        <?= $content; ?>
                    </td>
                    <td style="width: 50px"></td>
                </tr>
                <tr style="height: 50px">
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
            </tbody>
        </table>
    </body>
</html>