<table class="table">
    <thead>
        <tr>
            <th><?= $this->translate('id') ?></th>
            <th><?= $this->translate('role') ?></th>
            <th><?= $this->translate('parent.roles') ?></th>
        </tr>
    </thead>
    <tbody>
        <?php if ($paginator->count() < 1): ?>
        <tr>
            <td colspan="3"><?= $this->translate('no.results') ?></td>
        </tr>
        <?php endif ?>
        <?php foreach ($paginator->getCurrentItems() as $item): ?>
        <tr>
            <td><?= $item['id'] ?></td>
            <td><?= $item['name'] ?></td>
            <td><?= implode(', ', $item['parent']) ?></td>
        </tr>
        <?php endforeach ?>
    </tbody>
</table>