<?php if ($this->pageCount): ?>
<nav>
    <ul class="pagination">
        <?php if (isset($this->previous)): ?>
        <li>
            <a href="<?= $this->url($this->route, array('page' => $this->previous)) ?>">
                <span aria-hidden="true">&laquo;</span>
            </a>
        </li>
        <?php else: ?>
        <li class="disabled">
            <a href="#">
                <span aria-hidden="true">&laquo;</span>
            </a>
        </li>
        <?php endif ?>

        <?php foreach ($this->pagesInRange as $page): ?>
            <?php if ($page == $this->current): ?>
                <li class="active">
                    <a href="#"><?= $page ?></a>
                </li>
            <?php else: ?>
                <li>
                    <a href="<?= $this->url($this->route, ['page' => $page]) ?>">
                        <?= $page ?>
                    </a>
                </li>
            <?php endif ?>
        <?php endforeach ?>

        <?php if (isset($this->next)): ?>
        <li>
            <a href="<?= $this->url($this->route, array('page' => $this->next)) ?>">
                <span aria-hidden="true">&raquo;</span>
            </a>
        </li>
        <?php else: ?>
        <li class="disabled">
            <a href="#">
                <span aria-hidden="true">&raquo;</span>
            </a>
        </li>
        <?php endif ?>
    </ul>
</nav>
<?php endif ?>