<?php $this->headLink()->appendStylesheet($this->basePath('css/select2.min.css')) ?>
<?php $this->headScript()->appendFile($this->basePath('js/select2.full.min.js')) ?>
<h1><?= $this->translate('manage.profile.options') ?></h1>
<div class="row">
    <?= $this->form()->openTag($form) ?>
    <div class="col-xs-12">
        <?= $this->formRow($form->get('options')) ?>
    </div>
    <div class="col-xs-12">
        <?= $this->formElement($form->get('save')) ?>
    </div>
    <?= $this->form()->closeTag() ?>
</div>

<script type="text/javascript">
$('#options-select').select2({
    tags: true
});
</script>