<h1><?= sprintf($this->translate('profile.of.%s'), $displayName) ?></h1>
<?php if ($this->isAllowed('profileoption/list')): ?>
<a class="btn btn-xs btn-default" href="<?= $this->url('profileoption/list') ?>">
    <?= $this->translate('manage.profileoptions') ?>
</a>
<?php endif ?>
<?php if ($this->isAllowed('profile/edit')): ?>
<a class="btn btn-xs btn-default" href="<?= $this->url('profile/edit', ['id' => $userId]) ?>">
    <?= $this->translate('edit.profile') ?>
</a>
<?php endif ?>
<?php if ($this->isAllowed('auth/changePassword') && $identity == $userId): ?>
<a class="btn btn-xs btn-default" href="<?= $this->url('auth/changePassword') ?>">
    <?= $this->translate('change.password') ?>
</a>
<?php endif ?>
<?php if ($this->isAllowed('auth/selfDelete')): ?>
<a class="btn btn-xs btn-default" href="<?= $this->url('auth/selfDelete') ?>">
    <?= $this->translate('self.delete') ?>
</a>
<?php endif ?>
<table class="table">
    <tbody>
        <?php foreach ($profileData as $profileField): ?>
            <tr>
                <td><?= $this->translate($profileField['name']) ?></td>
                <td>
                    <?php if (!empty($profileField['value']) && $profileField['inputType'] == 'picupload'): ?>
                        <img src="<?= substr($profileField['value'], 6) ?>">
                    <?php else: ?>
                        <?= $profileField['value'] ?>
                    <?php endif ?>
                </td>
            </tr>
        <?php endforeach ?>
    </tbody>
</table>
